services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: userDb
      POSTGRES_PASSWORD: passwordDb
      POSTGRES_DB: nextjs-dashboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: